#planday project on automatizing the shift check process

rm(list = ls())

 # install.packages("tidyverse")
 # install.packages("cowplot")
 # install.packages("magick")
 # install.packages("tidytuesdayR")
 # install.packages("maps")
 # install.packages("janitor")
 # install.packages("patchwork")
 # install.packages("scales")
 # install.packages("ragg")
 # install.packages("urbnmapr")
 # install.packages("lubridate")
 # install.packages("showtext")
 # install.packages("ggimage")
 # install.packages("writexl")
 # install.packages("rstudioapi")
 # install.packages("png")


library(tidyverse)
library(cowplot)
library(magick)
library(tidytuesdayR)
library(maps)
library(janitor)
library(patchwork)
library(scales)
library(ragg)
library(urbnmapr)
library(lubridate)
library(showtext)
library(png)
library(ggimage)
library(writexl)
library(rstudioapi) 
library(readxl)


# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path)) 

#retrieve the wd so we can modify the path later for the volunteer database
a <- getwd()


#get the year and month of the shifts
#"/####/##-"

info <- str_extract(a, "/[[:digit:]]*/[[:digit:]]*-[[:alpha:]]*")
year <- str_extract(info, "^/[[:digit:]]*")
year <- gsub("/", "", year)
m <- str_extract(info, "[[:digit:]]*-")
m <- gsub("-", "", m)
month <- str_extract(info, "-[[:alpha:]]*")
month <- gsub("-", "", month)
#works

#get the number of days in a month

date1 <- paste0(year, "-", m, "-01")
date2 <- as.Date(date1, "%Y-%m-%d")
d <- lubridate::days_in_month(date2)
date3 <- paste0(year, "-", m, "-", d)

#create the file name that would be automatically generated by Planday
excelname <- paste0("First Department-", date1, "-", date3, ".csv")

#Download the excel file with the shifts 
#standard download

# #download shift data with proper UTF-8 encoding
# data <- read.csv("First Department-2022-02-01-2022-02-28.csv", sep=";", encoding = "UTF-8")

#automatic download of file
data <- read.csv(excelname, sep=";", encoding = "UTF-8")

#create employee planday name
#this variable might seem useless since the variable name exists, but while having a test 
#with other employees on how to run the script, we found out that if the name in planday
#has minor variations from the name of the persons, some people experience difficulties.
data$PlandayName <- str_c(data$EmployeeFirstName, " ", data$EmployeeLastName)
data$PlandayName <- gsub("[[:space:]][[:space:]]", " ", data$PlandayName)
data$PlandayName <- gsub("^[[:space:]]", "", data$PlandayName)
data$PlandayName <- gsub("[[:space:]]$", "", data$PlandayName)


#new naming code
data$Name <- str_c(data$EmployeeFirstName, " ", data$EmployeeLastName)
data$Name <- gsub("\\(.)", "", data$Name) 
data$Name <- gsub("[[:space:]][[:space:]]", " ", data$Name)
data$Name <- gsub("^[[:space:]]", "", data$Name)
data$Name <- gsub("[[:space:]]$", "", data$Name)

#create tokens for employee type and filled shift

bartender <- grepl("Bartenders", data$EmployeeGroupName, ignore.case = T)

data$bartender <- grepl("Bartenders", data$EmployeeGroupName, ignore.case = T)

shift <- grepl(".", data$EmployeeLastName, ignore.case = T)

data$shift <- grepl(".", data$EmployeeLastName, ignore.case = T)


#now create a new database with only filled shifts from bartenders

shifts <- filter(data, data$bartender==TRUE, data$shift==TRUE)
#works

#clean name data
#second attempt
shifts$name <- gsub("[[:space:]][[:space:]]", " ", shifts$name)
#works

#eliminate all useless variables
shifts <- subset(shifts, select = -c(bartender, shift, Administrative.note, PunchClockStartTime, PortalId,
                                     IsApproved, IsDraft, EmployeeMiddleName, PositionId, PositionName,
                                     ShiftSeriesGroupId, Comment, PunchClockEndTime, PortalName, EmployeeGroupId))

#shift list finished


#download file with bartender names

#create the pathway of the volunteer document

nopath <- str_extract(a, "[[:alpha:]]*/[[:digit:]]*-[[:digit:]]*/[[:digit:]]*/[[:digit:]]*-[[:alpha:]]*")
baselink <- gsub(nopath, "", a)
vol.link <- paste0(baselink, "VolunteerData")

setwd(vol.link)

#new download file with bartender names

file.list <- list.files(pattern='*.csv')
volunteers <- read.csv(file.list, sep=";", encoding = "UTF-8")


#now we got an issue. Windows and iOS systems read our excel files in different manners
#check if we are dealing with an apple user and modify our script accordingly

#check if the system is Windows
info1 <- Sys.info()
hit.sys <- grepl("Windows", info1, ignore.case = T)
df <- data.frame(info1, hit.sys)
sys <- head(df,1) 


#rename volunteers variable counting on operating system

volunteers$sys <- sys$hit.sys

volunteers$First.name[volunteers$sys == TRUE] <- volunteers$X.U.FEFF.First.name

#triple check database
#to do list:
# - divide employee.group into different variables or check names that are 
#   bartenders and eliminate the rest
# - clean unidentified characters in the dataset. (aka Ã¼ = ü)
##this tasks has already being applied by modifying the previous code


#filter results by people that have to get a shift
#check bartender list first, filter later

find.hits <- grepl("Bartenders|Organizers|Managers", volunteers$Employee.groups, ignore.case = T)

volunteers$find.hits <- grepl("Bartenders|Organizers|Managers", volunteers$Employee.groups, ignore.case = T)

vol.list <- filter(volunteers, volunteers$find.hits==TRUE)
#works
#finished

#start treating surname character identification
#it might all be done by changing text encoding to UTF-8
##this tasks has already being applied by modifying the previous code

#name variable
vol.list$Name <- str_c(vol.list$First.name, " ", vol.list$Last.name)
vol.list$Name <- gsub("\\(.)", "", vol.list$Name) 
vol.list$Name <- gsub("[[:space:]][[:space:]]", " ", vol.list$Name)
vol.list$Name <- gsub("^[[:space:]]", "", vol.list$Name)
vol.list$Name <- gsub("[[:space:]]$", "", vol.list$Name)

#planday name variable
vol.list$PlandayName <- str_c(vol.list$First.name, " ", vol.list$Last.name)
vol.list$PlandayName <- gsub("[[:space:]][[:space:]]", " ", vol.list$PlandayName)
vol.list$PlandayName <- gsub("^[[:space:]]", "", vol.list$PlandayName)
vol.list$PlandayName <- gsub("[[:space:]]$", "", vol.list$PlandayName)

#eliminate all useless variables
vol.list <- subset(vol.list, select = -c(Birthday, find.hits, X.U.FEFF.First.name, 
                                         Deactivation.date, Employee.type, Departments,
                                         Hired.date, Username))
#works
#volunteer database finished

#unite the two databases together
database <- left_join(vol.list,shifts, by=c("Name"="Name"))


#try with a dataset without data constrains and then left join it (mindblow)
s <- database %>% count(Name)

database2 <- left_join(database,s, by=c("Name"="Name"))
#genius move

#create the final dataset with limited variables and people with less than 3 shifts
final <- subset(database2, select = c(Name, Email, n, PlandayName.x, StartTime))

#if start time is NA, change n to 0

final$bad <- is.na(final$StartTime)
final$n[final$bad == TRUE] <- "0"

#drop unnecesary variables
final <- subset(final, select = c(Name, Email, n, PlandayName.x))

unique(final)

final <- unique(final)

#get averages of the last 3 months

#go back one month in time
f <- 01

s0 <- as.numeric(m)

s1 <- s0-f
s1[s1 == 0] <- 12
y1 <- as.numeric(year)
y1[s1 == 12] <- y1-f

s2 <- s1-f
s2[s2 == 0] <- 12
y2 <- y1
y2[s2 == 12] <- y1-f

#works

#create the working directory paths for previous months

basepath <- gsub(info, "", a)

m1 <- month.name[s1]

path1 <- paste0(basepath, "/", y1, "/", s1, "-", m1)
path1[s1<10]<- paste0(basepath, "/", y1, "/", "0", s1, "-", m1)

m2 <- month.name[s2]

path2 <- paste0(basepath, "/", y2, "/", s2, "-", m2)
path2[s2<10]<- paste0(basepath, "/", y2, "/", "0", s2, "-", m2)

#get data from previous wd

setwd(path1)

plist1 <- paste0("contact_list", "-", m1, y1, ".xlsx")

pshifts1 <- read_excel(plist1)

setwd(path2)

plist2 <- paste0("contact_list", "-", m2, y2, ".xlsx")

pshifts2 <- read_excel(plist2)

#create the average of shifts taken the last 3 months

pshifts1 <- pshifts1 %>%
        select(Name, n)

final <- left_join(final, pshifts1, by = "Name")
final$n_1 <- final$n.y
final$n <- final$n.x

final <- subset(final, select = -c(n.y, Email, n.x))

pshifts2 <- pshifts2 %>%
        select(Name, n)
final <- left_join(final, pshifts2, by = "Name")
final$n_2 <- final$n.y
final$n <- final$n.x

final <- subset(final, select = -c(n.y, Email, n.x))

final$sum <- as.numeric(final$n) + as.numeric(final$n_1) + as.numeric(final$n_2)

ag <- 3

final$avg <- final$sum/ag

final$avg <- format(round(final$avg, 2), nsmall = 2)

final <- subset(final, select = -c(sum, n.x, n.y, n_1, n_2))


#works

final[order(final$Name),]

final <- final[order(final$Name),]


setwd(a)

#save results in excel
finalname <- paste0("contact_list", "-", month, year, ".xlsx")
write_xlsx(final, finalname)

